### ISSUE TITLE
Codes of Conduct

### ISSUE THREAD

**Issue by omenking** [100DaysOfCloud/100DaysOfCloudBackend#10]
For the time being, this page is being hosted on Google Docs to make it easy for community members to comment and contribute. For our MVP I think we can just link to Google Doc instead of coding it into the Gatsby page.

We'll bring it over, but let's keep agility on the more important features and copywriting.

It is located here:
https://docs.google.com/document/d/1usk_eFB6eYL07z5dKANkUCdvnvFzifxjyuwi8Pkyk8A/edit

**Comment by omenking** [comment]
@cmgorton has but forward to adopt this:

https://www.contributor-covenant.org/

We get a badge if we adopt.
<img width="222" alt="Screen Shot 2020-07-05 at 7 14 36 PM" src="https://user-images.githubusercontent.com/7776/86544308-d817f300-bef3-11ea-9135-baa8d3394384.png">

It appears to be used by 200 open-source projects.
I'll have to give it a read to see if it's fit. If anyone else wants to look it over.

It's very odd they chose the word "Covenant" since that's an old bible term and you'd think they'd want to be neutral.  🤷‍♂️

**Comment by cmgorton** [comment]
I am discussing the Code of Conduct with Gywenth and Jenna tomorrow. Will put any updates here.
