### ISSUE TITLE
Current get_user_by_id Lambda code does not work

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudBackend#18]
@syedautherabbas
The current code in `sam/api` does not work well, or at all. I tried it on my machine and the tests don't run either. It has been merged because of outside reason but needs to be improved, it is high priority because we can't move further with improving the testing pipelines without test code. See #4 

This first will also establish the directory and test structure of all coming APIs, it's important to get this right.
The CloudFormation templates are already written and ready to go (see [sam/api.template.yml](https://github.com/100DaysOfCloud/100DaysOfCloudBackend/blob/dev/sam/api.template.yml)), only the code needs imrovement.

- Figure out and improve the folder structure of that folder. Do we put the tests in their own folder at the same level as the Lambda code? If yes, how can we import the Lambda code into the test.py? (it is notoriously complicated, it's a real question)
- Where **exactly** is `__init__.py` needed? Let's not have it where it's not neccessary.
- `AWS_DEFAULT_REGION` does not need to be specified in the Lambda code itself, it goes to the resources that are in the region the Lambda itself is in. It is however required for the tests, with that exact env variable name. It doesn't hurt, but it's just one more env variable we need to pass in just to be the same as the default.
- How does the URL path `https://api.com/users/{userID}` work and where is that `{userID}` stored in the request? In the `QueryStringParameters`? Or will the `github_username` be passed in the request body, in which case to we even need the `{userID}` URL path?
- this should go into the `get_user_details_by_Id` function so we don't need to pass it in extra. https://github.com/100DaysOfCloud/100DaysOfCloudBackend/blob/16e2cea1611299f508b893813f36ba8c88781d17/sam/api/get_user_by_id.py#L43 
- More allowed headers are required. `"Access-Control-Allow-Headers" : "Content-Type,X-Amz-Date,Authorization,X-Api-Key,x-requested-with",` as the APIs will likely use a Cognito authorizer. https://github.com/100DaysOfCloud/100DaysOfCloudBackend/blob/16e2cea1611299f508b893813f36ba8c88781d17/sam/api/get_user_by_id.py#L48

These are just a couple things from the top of my head, lets get this sorted together and with others' input as well, and we can move further.

## Current PyTest error with the CI GitHub Action:
<img width="926" alt="Screen Shot 2020-08-06 at 23 55 08" src="https://user-images.githubusercontent.com/20590073/89586585-45df7380-d840-11ea-99ea-023bb9652a40.png">
FYI, the GitHub Actions results (output) is only visible to users who have collaborator access on this repo. If you can't see it, that's why.

**Comment by syedautherabbas** [comment]
@what-name   please look at the originally suggested file structure on my fork. Then clone it and run pytest -v from the root. 
https://github.com/syedautherabbas/100DaysOfCloudBackend/tree/dev

 Do we put the tests in their own folder at the same level as the Lambda code? If yes, how can we import the Lambda code into the test.py? (it is notoriously complicated, it's a real question)
This is not ideal/best practice as tests should be maintained in their own modules. 
See below for visual representation. 

![image](https://user-images.githubusercontent.com/12937522/89740283-efbf3a00-daa4-11ea-8d45-3f9da180e10b.png)

Currently, we have only apis and so there is a single folder for test_api under tests, but as we keep adding more services we can add more folders for tests related to those services, for example - test_step_functions


Where exactly is __init__.py needed? Let's not have it where it's not necessary.
we need this file to declare a folder and its subdirectories as modules so they can be imported for testing. 


AWS_DEFAULT_REGION does not need to be specified in the Lambda code itself, it goes to the resources that are in the region the Lambda itself is in. It is however required for the tests, with that exact env variable name. It doesn't hurt, but it's just one more env variable we need to pass in just to be the same as the default.

I believe it is  *AWS_REGION* you are talking about in https://github.com/syedautherabbas/100DaysOfCloudBackend/blob/dev/sam/api/lambda_functions/get_user_by_id/get_user_by_id.py
if so, this is a quirk of moto and @antoniolofiego  is looking at how to make this env variable optional OR just remove it. But that said even if it somehow requires this env variable to run tests there is no harm as the Lambda won't break as AWS_REGION is passed by default. 

How does the URL path https://api.com/users/{userID} work and where is that {userID} stored in the request? In the QueryStringParameters? Or will the github_username be passed in the request body, in which case to we even need the {userID} URL path?

you are right we don't need this path param as the Lambda will get the username as a query param from API-G, I will fix the template and send a new PR as the old one is already merged.
