### ISSUE TITLE
Get a Skeleton Gatsby project setup with AWS Amplify deployed to AWS Amplify Console

### ISSUE THREAD

**Issue by omenking** [100DaysOfCloud/100DaysOfCloudBackend#2]
Gatsby has a build setup.
I wonder how we can trigger a build setup with AWS Amplify Console.
Right now the goal is to determine technical uncertainty between Gatsby and Amplify before adding features

**Comment by rishabkumar7** [comment]
I think we can have two approaches to the CI/CD pipeline, at-least that I can think of!
**AWS Amplify**

- Deploy the Gatsby site with AWS Amplify.

**AWS CodePipeline**

- We can use Github Repo as source
- And Deploy it to S3 bucket, since the site is already live with S3 and CloudFront.

Both approach seems to work, I personally have tested the Amplify and will document it below, will do the same for CodePipeline later.

**Comment by omenking** [comment]
My experience with AWS Amplify Console so far is that it reduces the number of steps.
I am uncertain of what other limitations there are AWS Amplify Console.

**Comment by rishabkumar7** [comment]
## **AWS Amplify** approach
Log into the [Amplify Console](https://console.aws.amazon.com/amplify/home).

From here, under Deploy we can click GET STARTED:

Next, we’ll choose GitHub as our repository & click **Next**.

![image](https://user-images.githubusercontent.com/45825464/86502325-e937f700-bd6f-11ea-94c0-240aea415d90.png)

Then connect the mater branch of the new repo we just created & click **Next**:
![image](https://user-images.githubusercontent.com/45825464/86502330-05d42f00-bd70-11ea-954c-dfb1b8b659e7.png)

In this view, we can review the default build settings & click **Next** to continue:
![image](https://user-images.githubusercontent.com/45825464/86502335-0e2c6a00-bd70-11ea-9bff-32fd5b668089.png)

Finally, we can review the deployment & click **Save & Deploy** when we’re ready to deploy our app:
![image](https://user-images.githubusercontent.com/45825464/86502341-243a2a80-bd70-11ea-925c-8d47231e0e7e.png)


Once the deployment is successful, you should see this:
![image](https://user-images.githubusercontent.com/45825464/86502346-30be8300-bd70-11ea-979d-496f5913f8cf.png)


## **Kicking off a new build**

Now that our app is deployed, let’s take it one step further. The Amplify Console will automatically watch your master branch & kick off a new build whenever new code is merged. Let’s test this out.

Open `src/pages/index.js` & replace the following line:

`<h1>Hi people</h1>`

with this:

`<h1>Hi #100DaysOfCloud community</h1>`

Save the file & push the changes to your master branch:

`git add .
git commit -m 'updated heading'
git push origin master`

Now, when we go back into the Amplify console we’ll see that a new build has been started:

When the build is completed & we launch the app, we should now see our new heading
![image](https://user-images.githubusercontent.com/45825464/86502349-3e740880-bd70-11ea-8fb8-2cf2807bdb35.png)

**Comment by rishabkumar7** [comment]
## AWS CodePipeline approach

Go to CodePipeline from the console → click ‘Create pipeline’ → create pipeline name (e.g. my-website-project) → choose Service role → click ‘Next’.
Service Role
Choose ‘New service role’. The Role name will be auto-filled when we type in the Pipeline name
![image](https://user-images.githubusercontent.com/45825464/86519024-ad02a600-be04-11ea-9ad4-3371ba2095c7.png)

Choose GitHub for your source → connect your GitHub and choose the right repository → choose branch → select GitHub webhooks (selected by default) → click ‘Next’.
![image](https://user-images.githubusercontent.com/45825464/86519028-bb50c200-be04-11ea-853d-3da366c4e0ab.png)


Choose AWS CodeBuild for Build provider → click ‘create project’ (a new window will pop-up.
![image](https://user-images.githubusercontent.com/45825464/86519032-c99ede00-be04-11ea-91db-02c72b2a8940.png)
![image](https://user-images.githubusercontent.com/45825464/86519033-d1f71900-be04-11ea-814f-d0cc330d22fc.png)

→ Type in ‘Project name’ → select ‘Managed image’, then a new section will show up → choose ‘Standard’ for Runtime → choose ‘standard:2.0’ for Image → leave the rest as they are and find ‘Service role’ → select ‘Existing service role’ → find the role that we created.

![image](https://user-images.githubusercontent.com/45825464/86519036-dde2db00-be04-11ea-98bf-2023849400af.png)

**Comment by omenking** [comment]
So for the CodePipeline is this just deploying Gatsby, so there is no AWS Amplify?

**Comment by mtliendo** [comment]
Love the detailed overview of each path!

@omenking Yup, with codepipeline it would remove the amplify console part, which also means we would likely want to use a more generic Gatsby starter if going that route.

A couple of notes regarding AWS Amplify in terms of using it in open source:

* If just using it as ci/cd platform, the Amplify console (not the [amplify cli](https://docs.amplify.aws/cli)) is a great choice
* If wanting to use the amplify cli as well, it's good to keep in mind that any contributor will need an AWS account--which given that 100DaysOfCloud is also supporting Google and Azure, may be a barrier to contributors
* Regarding Andrew's question on other limitations, while relatively minor, keep in mind the [pricing model](https://aws.amazon.com/amplify/pricing) since we may want to have a staging/develop branch that also get updated on commit as well.

Is the intent for it to be a static site or are there serverless features (auth, api, etc) that the site will need? Just bringing it up because it may be best to discuss features of the site and let that dictate what stack is best.

**Comment by omenking** [comment]
## Dynamic of Static

There will be dynamic components, so I think serverless will be part of the equation. 
We have an accompanying Git Repository that they fork that is part of the challenge and we want to pull people's progress:
https://github.com/100DaysOfCloud/100DaysOfCloud

So the idea is that we can show a journey board of participants based on monitoring their repo.

There could be the utility of having IdP for Twitter or Github so adding something such as Cognito may be in the development roadmap.

## Agnosticism 

Making note of that barrier. I want to sit this challenge up in days, and if we go the Serverless Framework we can get some agnosticism with computing, though when it comes to databases, and authentication we're going to have to make a choice unless we sit everything up in micro-services with containers and then I see our time-line stretching and stretching. 

I think for the scope of this challenge page may be better to go AWS here and we should rotate out clouds so we have more opportunities. I don't foresee this project to be the only cloud project.  

## Pricing

I just received a fresh round of AWS Credits, So I currently feel incentivized to host on AWS. 🙃

The cost to contributors with AWS right now is pennies, so I would say if this platform becomes more than expected we'll have to address these and migrate to an ultra cost-sensitive solution. If contributors could run an entire local environment that would mitigate any costs. 

I think the general rule with Serverless is to run development workloads on the cloud because local development is not reliable, though I could be unaware of better serverless solutions.

**Comment by rishabkumar7** [comment]
For now, the site is deployed via amplify!
https://master.d1igfgwt2o399m.amplifyapp.com/
![image](https://user-images.githubusercontent.com/45825464/86652217-34d9e300-bfb2-11ea-940a-59d5a9c30d10.png)

**Comment by what-name** [comment]
The Amplify App is being deprecated already. Close issue?

**Comment by rishabkumar7** [comment]
@what-name Closing this issue, since moving to serverless.
