### ISSUE TITLE
Add 100DaysOfCode videos to homepage.

### ISSUE THREAD

**Issue by rishabkumar7** [100DaysOfCloud/100DaysOfCloudBackend#24]
@madebygps created some amazing video on how to start the #100DaysOfCloud challenge, its a good idea to add them to the homepage so that newcomers know where to start and how to start.

**Comment by madebygps** [comment]
Yes, ideally we have a somewhere we can just link to and people will get all info they need to get started.

**Comment by rishabkumar7** [comment]
https://github.com/100DaysOfCloud/100DaysOfCloudBackend/pull/25
