### ISSUE TITLE
The Sitemap

### ISSUE THREAD

**Issue by omenking** [100DaysOfCloud/100DaysOfCloudBackend#3]
<img width="1031" alt="Screen Shot 2020-07-05 at 7 07 08 PM" src="https://user-images.githubusercontent.com/7776/86544183-c550ee80-bef2-11ea-8287-6fa28c3fd154.png">

| Issue | Name | Path |  Description |
|---|---|---|---|
| #4 | Home | / | The homepage I think can be a feed of both articles and status updates. We can have a tag list on the right-hand side and highlight new or expectational users   |
| #5  | Cloud Journeyers | /cloud-journeyers | This will be a list of all participants order by most active |
| #6 | Article | /u/:username/:slug | Articles, for the time being, will have to accepted and published via Pull Requests.  |
| #7 | Profile | /u/:username | We can have their [Github Cloud Journey Fork](https://github.com/100DaysOfCloud/100DaysOfCloud) be their profile. We'll just code in a redirect to their page. We can keep it simple and just store their github username.  |
| #8 | FAQs |  /faqs |  For the time being, we can just link to the Google Docs FAQs |
| #9 | Rules |  /rules |  For the time being, we can just link to the Google Docs  Rules |
| #10  | Codes Of Conduct |  /code-of-conduct |  For the time being, we can just link to the Google Docs Codes of Conduct  |
| #11 | Tag Articles | /t/:tag | This just listing all related status updates and articles for the given tag  |
|   | About Page |  /about |  Its what you think it might be lol. |

Notice that I have scoped some URLs with prefixes eg. "/u", "/t" This is to avoid conflicts where someone's username could be the same as tag or an article slug.

For the Google Docs I have placed them in this Google Folder and its set to be viewable by anyone.
https://drive.google.com/drive/folders/1c5RdNNodK9YJNV0nxGVXVPmC5nuW8T2-?usp=sharing

**Comment by omenking** [comment]
Please put forward for any suggestions if there is anything missing from the Sitemap

**Comment by omenking** [comment]
I have now linked up all pages to Github Issues and further detail the pages. 
Hopefully down to the component level.

**Comment by what-name** [comment]
I think a page full of ideas on what to build would be very beneficial. Myself and possibly a lot of beginners struggle with this, and in my opinion [mini-]projects are the best way to learn and stretch your wings. Maybe even backed by some how-tos.

**Comment by antoniolofiego** [comment]
> I think a page full of ideas on what to build would be very beneficial. Myself and possibly a lot of beginners struggle with this, and in my opinion [mini-]projects are the best way to learn and stretch your wings. Maybe even backed by some how-tos.

I agree with this. I have always struggled with finding good entry level project ideas at the beginning of any learning process because I never knew what was possible. 

For example, something I am currently participating in is the Cloud Resume Challenge by Forrest Brazeal, which gives a list of general tasks to complete to set up a personal website on CloudFront/S3 and a serverless API to keep track of visitors. 

If we can pull ideas, it's probably a great way to get newcomers started right away and not let them be lost in tutorial hell.

**Comment by what-name** [comment]
@antoniolofiego yes, here is the [seperate github repo for the ideas](https://github.com/100DaysOfCloud/100DaysOfCloudIdeas). It's better to have those ideas in one central place that provides easy collaboration. Contributions are welcome. Hosting them on the website would cause much more friction.

**Comment by antoniolofiego** [comment]
Currently done with a good shell for Home and Article. Will work on the Profile and Journeyers pages today.
