### ISSUE TITLE
CI/CD pipeline for the Frontend

### ISSUE THREAD

**Issue by what-name** [100DaysOfCloud/100DaysOfCloudBackend#7]
### Info
[The frontend repository can be found here.](https://github.com/100DaysOfCloud/100DaysOfCloudFrontend)
There is currently no pipeline whatsoever or even a deployment of the new frontend. To be able to work on both the front and backend, there needs to be a complete `dev` environment deployed incorporating both.

The pipeline is very similar to the current `cicd/codepipeline-dev.template.yaml` template and could even be incorporated into that. I'm not sure if we should have two seperate and isolated pipelines for deploying changes in either the frontend or backend repositories, or the same pipeline should deploy everything together when changes are made in either of the repositories.

1. Decoupled and seperate deployments
vs.
2. coupled and coordinated deployments

**Comment by rishabkumar7** [comment]
@what-name I would love to implement this if we decide to do a separate pipeline for frontend.

**Comment by antoniolofiego** [comment]
We should move this to the frontend repo.

**Comment by antoniolofiego** [comment]
Closing. Moved to frontend repo at https://github.com/100DaysOfCloud/100DaysOfCloudFrontend/issues/26
