### ISSUE TITLE
FAQs Page

### ISSUE THREAD

**Issue by omenking** [100DaysOfCloud/100DaysOfCloudBackend#8]
For the time being, this page is being hosted on Google Docs to make it easy for community members to comment and contribute. For our MVP I think we can just link to Google Doc instead of coding it into the Gatsby page.

We'll bring it over, but let's keep agility on the more important features and copywriting.

It is located here:
https://docs.google.com/document/d/1U9Iyp2y-3eEW3OyV5O9bQrsj9qXl8S3Cxz-cPRruspM/edit

**Comment by omenking** [comment]
I have populated some questions for the FAQs
@cmgorton would you do me the favour and provide the copy for the answers.

**Comment by cmgorton** [comment]
Sure. I'll work on this tomorrow 😀
